name = "dr"
license = "MIT"
licenselink = "https://github.com/"
description = "Portfolio Template (Archived)"
homepage = "https://netlify.com"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'dark', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography', 'somratpro']
features = ['bootstrap','responsive']
min_version = "0.60.0"

[author]
  name = "deepanshu"
  homepage = "https://netlify.com/"
